dist: xenial
notifications:
  email: false

language: scala
jdk:
  - openjdk8
  - openjdk11

scala:
  - 2.13.1

services: postgresql

addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12


before_script:
  - psql -c "ALTER USER travis WITH PASSWORD 'travis';"
  - psql -c "CREATE EXTENSION pgcrypto;"
  - psql -c "CREATE EXTENSION hstore;"
  - cp ore/conf/application.conf.template ore/conf/application.conf
  - cp jobs/src/main/resources/application.conf.template jobs/src/main/resources/application.conf

env:
  global:
    - PGPORT=5433
    - DB_USERNAME=travis
    - DB_PASSWORD=travis
    - DB_DATABASE=travis

# Caching taken from https://www.scala-sbt.org/1.0/docs/Travis-CI-with-sbt.html#Caching
cache:
  directories:
    - $HOME/.cache/yarn
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier/cache

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

script:
  - sbt ++$TRAVIS_SCALA_VERSION ";oreAll/compile; ore/test ;ore/assets"
  - ./scalafmt --check --non-interactive
